sudo: false
language: go
env:
  global:
  - GO111MODULE=on
go:
- stable
install: true
jobs:
  include:
  - stage: test
    script:
    - go mod vendor
    - go test -covermode=count -coverprofile=coverage.out -v ./...
    after_success:
      - bash <(curl -s https://codecov.io/bash)
