codecov:
  token: ""
  bot: "codecov-io"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: no
  notify:
    after_n_builds: 2
    wait_for_ci: yes
